Prefix: "&7[&c&lUHC&7]&r" #Prefix of chat
Spawn: # Spawn coordinates
  x: 0.5 # float
  y: 250 # int
  z: 0.5 # float

LengthDay: 20 # Lenght of a day in minutes
DayLightCycle:
  Enable: false # Infinite day if false
  Hour: 6000 # If infinite day, time of the day to stay at

Scoreboard:
  Enable: true # enable the scoreboard or not
  Title: "UHC Commando"
  ShowPlayers: true # Display remainings player amount or not
  ShowTeams: true # Display remaining teams or not
  ShowDay: true # Display the current day
  ShowTimer: true # Display the current of the party

TabHealth: true # Show health in tab board
TpToSpawnIfStart: true # Teleport player to spawn if joining after start
SpecIfStart: true # Set to spectator player if joining after start
Achievement:
  DisableBeforeStart: true # Disable achievements before the beginning of the game
  ResetOnStart: true # Reset achievements at the start
  
NotifIfTeamsFall: true # annoncer quand une team est vaincu
Death:
  Lightning: false # Summon a lightning at the player death position
  Sound: true # Play a sound at the death of a player

BadWeather: false # Bad weather (rain) disabled if set to 
NotchApple: false # Allow or not notch apples
LevelTwoPotions: false # Allow or not potion of level 2
StrenghtPotions: false # Allow or not strenght potion
ProjectilesKnockback: false # Allow or not fishing rod, snowball and eggs knockback for PvP

Teams:
  RandomTeam: true # Generates random team or not
  FriendlyFire: true # Enable or not friendly fire
  DisplayJoinTeamMessage: true # Show message to join team on loggin before start
  TimeBeforeSend: 2 # Time before sending the above message
  TeamChat: true # Enable or not team chat
  TeamsName:  {"Dark Red", "Red", "Orange", "Yellow", "Dark Green", "Green", "Aqua", "Dark Blue", "Blue", "Pink",         "Purple",      "White"}
  TeamsColor: {"dark_red", "red", "gold",   "yellow", "dark_green", "green", "aqua", "dark_blue", "blue", "light_purple", "dark_purple", "white"}
  TeamsColorCode: {"&4",   "&c",  "&6",     "&e",     "&2",         "&a",    "&b",   "&1",           "&9",    "&d",           "&5",          "&f"}

Invicibility: 30 # Invicibility time at the start of the game, in seconds
TimeBeforePvp: 20 # Time in minutes before PVP is enable

Border:
  StartSize: 2000 # Initial size of the border
  TimeBeforeMoving: 60 # Amount of time in minutes before the border starts moving
  EndSize: 500 # Final size of the border
  MovingDuration: 1200 # Moving time of the border in seconds