Prefix: "&7[&c&lUHC&7]&r" #Prefix of chat
WorldName: "world" # Name of the world played in
Spawn: # Spawn coordinates
  x: 0.5 # float
  y: 250 # int
  z: 0.5 # float

LengthDay: 20 # Lenght of a day in minutes
DayLightCycle:
  Enable: false # Infinite day if false
  Hour: 6000 # If infinite day, time of the day to stay at

ScoreboardTitle: "UHC Commando"

TabHealth: true # Show health in tab board
SpecIfStart: true # Set to spectator player if joining after start
Achievement:
  DisableBeforeStart: true # Disable achievements before the beginning of the game
  ResetOnStart: true # Reset achievements at the start
  
NotifIfTeamsFall: true # annoncer quand une team est vaincu
Death:
  Lightning: false # Summon a lightning at the player death position
  Sound: true # Play a sound at the death of a player

BadWeather: false # Bad weather (rain) disabled if set to 
NotchApple: false # Allow or not notch apples
LevelTwoPotions: false # Allow or not potion of level 2
StrenghtPotions: false # Allow or not strenght potion
ProjectilesKnockback: false # Allow or not fishing rod, snowball and eggs knockback for PvP
AllowNether: true # Allow or not the nether
AllowHorse: true # Allow or not horses
FireAndFlame: true # Allow or not fire aspect and flame enchantments
CutClean: false # Enable or not the Cut Clean scenario (autosmelting items)

Teams:
  RandomTeam: true # Generates random team or not
  FriendlyFire: true # Enable or not friendly fire
  DisplayJoinTeamMessage: true # Show message to join team on loggin before start
  TimeBeforeSend: 2 # Time before sending the above message
  TeamChat: true # Enable or not team chat
  Teams: # color,symbol,name - splitted by comma
    - "DARK_RED,#,Dark Red"
    - "RED,#,Red"
    - "GOLD,#,Orange"
    - "YELLOW,#,Yellow"
    - "DARK_GREEN,#,Dark Green"
    - "GREEN,#,Green"
    - "AQUA,#,Aqua"
    - "DARK_BLUE,#,Dark Blue"
    - "BLUE,#,Blue"
    - "LIGHT_PURPLE,#,Pink"
    - "DARK_PURPLE,#,Purple"
    - "GRAY,#,Gray"
    - "WHITE,#,White"

Invicibility: 30 # Invicibility time at the start of the game, in seconds
TimeBeforePvp: 20 # Time in minutes before PVP is enable

Border:
  StartSize: 2000 # Initial size (width) of the border
  TimeBeforeMoving: 60 # Amount of time in minutes before the border starts moving
  EndSize: 500 # Final size of the border
  MovingDuration: 1200 # Moving time of the border in seconds