name: UHC_Commando
version: ${project.version}
main: com.commando.uhc_commando.UHC_Commando
commands:
  alert:
    description: Create a broadcast message
    usage: /alert <message>
    permission: perm.use
  rule:
    description: Rules of the UHC
    usage: /rule <1>... <?>
  start:
    description: Start the game
    usage: /start
    permission: perm.use
  createSpawn:
    description: Create the spawn plateform
    usage: /createSpawn
    permission: perm.use
  inv:
    description: See the inv of a player (You are able to take the item)
    usage: /inv <Pseudo>