name: UHC_Commando
version: ${project.version}
main: com.commando.uhc_commando.UHC_Commando
commands:
  alert:
    description: Create a broadcast message
    usage: /alert <message>
    permission: perm.use
  rule:
    description: Rules of the UHC
    usage: /rule <1>... <?>
  start:
    description: Start the game
    usage: /start
    permission: perm.use
  createSpawn:
    description: Create the spawn plateform
    usage: /createSpawn
    permission: perm.use
  join:
    description: Join a team
    usage: /join <team>