name: UHC_Commando
version: ${project.version}
main: com.commando.uhc_commando.UHC_Commando
commands:
  alert:
    description: Create a broadcast message
    usage: /alert <message>
    permission: perm.use
  rule:
    description: Rules of the UHC
    usage: /rule <1 -> 5>
  start:
    description: Start the game
    usage: /start
    permission: perm.use
  inv:
    description: See the inventory of a player (You can interact with it)
    usage: /inv <Pseudo>